import type { NextPage } from 'next'
import Head from 'next/head'
import FeaturedPost from '../components/FeaturedPost'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AlgaNews - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Aprendendo <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <FeaturedPost postSummary={
          {
            "id": 1,
            "title": "Você sabe como é trabalhar em uma startup?",
            "slug": "voce-sabe-como-e-trabalhar-em-uma-startup",
            "imageUrls": {
              "small": "http://localhost:8080/downloads/posts/small/voce-sabe-como-e-trabalhar-em-uma-startup.jpg",
              "medium": "http://localhost:8080/downloads/posts/medium/voce-sabe-como-e-trabalhar-em-uma-startup.jpg",
              "large": "http://localhost:8080/downloads/posts/large/voce-sabe-como-e-trabalhar-em-uma-startup.jpg",
              "default": "http://localhost:8080/downloads/posts/voce-sabe-como-e-trabalhar-em-uma-startup.jpg"
            },
            "published": true,
            "tags": [
              "Java",
              "ReactJS",
              "Javascript"
            ],
            "createdAt": "2021-08-19T23:51:29Z",
            "updatedAt": "2021-08-19T23:51:29Z",
            "canBePublished": false,
            "canBeUnpublished": false,
            "canBeDeleted": false,
            "canBeEdited": false,
            "editor": {
              "id": 6,
              "name": "Débora Mendonça",
              "avatarUrls": {
                "small": "http://localhost:8080/downloads/photos/small/avatar-debora.jpeg",
                "medium": "http://localhost:8080/downloads/photos/medium/avatar-debora.jpeg",
                "large": "http://localhost:8080/downloads/photos/large/avatar-debora.jpeg",
                "default": "http://localhost:8080/downloads/photos/avatar-debora.jpeg"
              },
              "createdAt": "2021-02-20T23:51:29Z"
            }
          }
        } />

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
