import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { Post, PostService } from 'rodolfohiok-sdk';
import FeaturedPost from '../components/FeaturedPost';

interface HomeProps {
  posts: Post.Paginated;
}

const Home: NextPage<HomeProps> = (props: HomeProps) => {
  const { posts } = props;
  return (
    <div>
      <Head>
        <title>AlgaNews - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { 
        posts?.content &&
        <FeaturedPost postSummary={posts.content[0]} />
      }

    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  context
) => {
  const { page } = context.query;
  const posts = await PostService.getAllPosts({ page: Number(page) - 1 });

  return {
    props: {
      posts,
    }
  }
}
